### PR TITLE
testbech32 requires rapidcheck to build

### PR DESCRIPTION
**Pull request by madMAx43v3r**

### CODE REVIEW

**Comment by danpape** [comment]
Ah, good catch. Our other projects that include libbech32 already use rapidcheck for their own tests, so that must be why I never noticed this would not work the way I had it set up. I'll have to test this out with those projects before I can determine if I can merge this in. Thanks for the PR, please stand by.

**Comment by madMAx43v3r** [comment]
Yeah, maybe there's a better way to fix it.

**Comment by danpape** [comment]
Hey @madMAx43v3r would you mind letting me know what sort of error you were seeing that caused you to want to make this change? I've been testing things with some of our other projects that include libbech32 (and a dummy project I just made) in order to try out different options, but I don't see any variant that would need this change to be made. Perhaps I'm just not doing it the same way. I took a look at your chia-plotter project and it seems good to me.

**Comment by madMAx43v3r** [comment]
The repo is here: https://github.com/madMAx43v3r/mmx-node
You can checkout master branch for libbech32 and see the error. It's caused by these settings:
```
set(LIBBECH32_BUILD_GOOGLETEST OFF CACHE BOOL "LIBBECH32_BUILD_GOOGLETEST")
set(LIBBECH32_BUILD_RAPIDCHECK OFF CACHE BOOL "LIBBECH32_BUILD_RAPIDCHECK")
```
(I want to clean up the build process, hence I disabled the tests)

**Comment by danpape** [comment]
Hey @madMAx43v3r , it seems to me that what I should do is add a BUILD_LIBBECH32_TESTS option, then all you need to do is set that to OFF in your CMakeLists.txt, then you won't have to worry about my googletest or rapidcheck dependencies. I'll make that change asap and let you know when you can update your libbech32 submodule.

**Comment by madMAx43v3r** [comment]
Yeah that'll work

**Comment by danpape** [comment]
Hey @madMAx43v3r I'm going to close this as I fixed the problem in a slightly different way. I've opened https://github.com/madMAx43v3r/mmx-node/pull/33 for you. Thanks.

**Pull request closed without merging**
